nknorg/tuna

- bin/entry/main.go
- bin/exit/main.go
- config.entry.json
- config.exit.json
- entry.go
- exit.go
- geo.go
- tests/geo_test.go
- tuna.go
* Implement payment for reverse tuna using nanopay
* Add geolocation filter to select service IP address
> Implement reverse tuna payment and geo IP filter

- entry.go
- exit.go
- tuna.go
> Reduce payment timeout check interval and change traffic coverage time

- config.exit.json
- exit.go
> Rename IPFilter -> ReverseIPFilter in exit config

- bin/entry/main.go
- bin/exit/main.go
- entry.go
- exit.go
> Add ReverseServiceName and ReverseSubscriptionPrefix in config

- tuna.go
> Change type byte to uint8 to avoid gomobile compile error

- entry.go
- tuna.go
> Change meta service id to int type for gomobile compatibility

- geo.go
> Fix ip2c results being ignored

- entry.go
- exit.go
- tuna.go
> Fix exit disconnect even when price is zero

- config.entry.json
- config.exit.json
- entry.go
- exit.go
- geo.go
- tuna.go
> Change config field first letter to non-capitalized

- entry.go
> send channel is not closed.

- README.md
> Add UDP WIP note in readme

- Makefile
> Add support for 32bit arm version (v5, v6, v7)

- cmd/entry.go
- cmd/exit.go
> Add cli options to enable reverse mode

- go.mod
- go.sum
> Change encrypted-stream version to v1.0.0

- config.entry.json.example
- config.exit.json.example
- go.mod
- go.sum
- tuna.go
> Will not subscribe if same subscription exists

- entry.go
- exit.go
- tuna.go
- util.go
> Entry OnConnect will fire every time conn reconnects

- util.go
> Fix onconnect channel isclosed not set on close

- tuna.go
> Shuffle subscribers to get true random order

- tuna.go
> Prevent indefinitely trying to send nanopay if conn is closed

- cmd/entry.go
- cmd/exit.go
- entry.go
- exit.go
> Prevent reverse entry not close

- tuna.go
> Provider will only disconnect if unpaid traffic > 1MB

- cmd/entry.go
- cmd/exit.go
- cmd/main.go
> Add cli options to change seed rpc server address

- go.mod
- go.sum
> Upgrade nkn-sdk-go version

- entry.go
- exit.go
> Improve logs on accept error

- geo/aws.go
- geo/gcp.go
- geo/geo.go
- geo/geolite.go
> Improving update geo db logs

- geo/aws.go
- geo/gcp.go
- geo/geolite.go
- util/util.go
> Use geodb directory as temp dir when downloading to avoid permission issue

- geo/aws.go
- geo/gcp.go
- geo/geolite.go
> Fix wrong tmp dir when geodb directory is ./

- geo/geolite.go
> Use github mirror link

- tuna.go
> Remove unused mutex lock

- entry.go
- exit.go
- tuna.go
- types/node.go
> Add config to sort measured nodes by external caller

- entry.go
- exit.go
- tuna.go
> Add config to change measure bandwidth timeout

- storage/measure.go
> Fix race condition in measurement storage

- tuna.go
> Fix the bug that bandwidth measurement may take longer than timeout

- entry.go
> Allow reverse entry to specify multiple reverse service name

- entry.go
- exit.go
- tuna.go
- util.go
> Add limit to metadata size to prevent memory bomb

- tuna.go
> Reduce pipeBufferSize to be compatible with c++ smux

- storage/measure.go
- tuna.go
> Delete favorite node before adding to avoid delete added node

- entry.go
- exit.go
- geo/geo.go
- tests/geo_test.go
- tests/storage_test.go
- tuna.go
> Reload measure storage every time to support multiple tuna instance

- storage/measure.go
- tuna.go
> Reduce measureBandwidthTopCount and favorite node size

- tuna.go
- types/node.go
> Fix delay measure results not sorted

- tuna.go
> Use all delay measure results instead of first batch

- cmd/entry.go
- cmd/exit.go
- tuna.go
- types/node.go
- util.go
> Use favorite node as seed node

- entry.go
- exit.go
- tuna.go
> Add linger logic before close and api to set linger

- cmd/entry.go
- cmd/exit.go
- config.go
- entry.go
- exit.go
- go.mod
- tuna.go
> Simplify config code structure

- .gitignore
- cmd/entry.go
- cmd/exit.go
- entry.go
- storage/measure.go
- tests/measurement_test.go
- tests/storage_test.go
- tuna.go
- util.go
> Use per service measurement storage to avoid mixing nodes

- filter/nkn_filter.go
- tuna.go
> Add metadata field to nkn filter to bypass rpc call

- tuna.go
> Add retry interval when dial to server error

- config.entry.json.example
- config.exit.json.example
> Update default price in config example

- cmd/entry.go
- cmd/exit.go
> Fix empty seed rpc address when measure bandwidth is disabled

- tuna.go
> Reduce getsubscribers api call when there are few subscribers

- config.go
- tuna.go
> Fix using 0x00 prefix hash when sub count is less than default count

- config.go
- exit.go
> Test conn on reverse exit before choose entry node

- exit.go
> Close test conn on reverse exit

- cmd/entry.go
- cmd/exit.go
- entry.go
- exit.go
- tuna.go
> Share the same client for reverse entry

- entry.go
- exit.go
- tuna.go
> Prevent payment stream created multiple times and recipient race condition

- config.go
- encryption.go
- entry.go
- exit.go
- go.mod
- go.sum
- tuna.go
- util/measurement.go
Add measure bandwidth timeout on server side to reduce close wait connection count
> Add measure bandwidth timeout on server side

- config.entry.json.example
- config.exit.json.example
- config.go
- entry.go
- exit.go
- subqueue.go
- tuna.go
* Check sub status periodically to handle sub failure
* Use sub fee only if wallet has enough balance
* Add config to replace txpool when subscribing
> Better handling of txn fee and subscription failure

- tuna.go
> Optimize the number of RPC calls when sub count is small

- go.mod
- go.sum
- subqueue.go
> Fix sub txn not replaced if nonce is 0

- README.md
> Update gomobile doc

- geo/gcp.go
- geo/geolite.go
> update gcp and geolite db url

- tuna.go
> Stop connect retry after tuna is closed

- errors.go
- exit.go
- tuna.go
> Bug fix: tuna might not exit when closed

- cmd/entry.go
- config.go
- entry.go
- exit.go
- tests/util.go
- tuna.go
- udp.go
- util.go
mv udp code to the root dir of tuna
> mv udp code to the root

- entry.go
- util.go
Fix udp started before local variables which udp needed available
> fix udp started before local variables available

- entry.go
- go.mod
- go.sum
- tests/config.forward.entry.json
- tests/config.reverse.exit.json
- tests/entry_test.go
- tests/services.entry.json
- tests/services.exit.json
- tests/services.reverse.exit.json
- tests/util.go
- tuna.go
- udp.go
1. Drop unencrypt message except for metadata
2. Add more tests for both encrypt and unencrypted client
> Drop unencrypt message except metadata and add more tests

- udp.go
> Fix thread unsafe codec for UDP encode and decode

- config.go
- entry.go
- exit.go
- tuna.go
1. Add minBalance in entry and exit config;
2. Check wallet balance in tuna.CreateServerConn. If wallet balance is less than config minBalance, connection would be rejected.
> Check wallet balance in CreateServerConn

- config.go
- entry.go
- util/measurement.go
Fix deadlock when udp connection block tcp, and using `SetLinger(0)` to avoid to many CLOSE_WAIT / TIME_WAIT issue
> Tcp deadlock fix

- entry.go
> setlinger & close EOF tcp conn
